export const en = {
  nav: { about: "About", experience: "Experience", projects: "Projects", skills: "Skills", contact: "Contact", downloadCv: "Download CV", openMenu: "Open navigation menu", closeMenu: "Close navigation menu" },
  hero: { availability: "Available for opportunities", role: "Software Engineer | Web & Mobile", description: "I design and build scalable web and mobile products, combining software engineering, performance, and user experience.", technologies: "Flutter · React · Angular · TypeScript", viewProjects: "View Projects" },
  about: { eyebrow: "About", title: "About me", paragraphs: ["Computer Systems Engineer with professional experience building web and mobile products using Flutter, React, Angular, JavaScript, TypeScript and Dart.", "I have worked on international products integrating REST APIs, payments, OAuth authentication, maps, push notifications, WebSockets and third-party services.", "I enjoy building maintainable products, solving complex problems and creating intuitive user experiences."] },
  experience: { eyebrow: "Career", title: "Professional Experience", entries: [
    { company: "SPORTYEAH", role: "Mobile Software Developer", period: "Aug 2025 – Present", responsibilities: ["Develop and maintain the Sportyeah mobile application using Flutter and Dart.", "Develop and improve tournament, club, profile and store modules.", "Integrate Google ecosystem services and iOS services.", "Improve user flows, interfaces and overall mobile UX."] },
    { company: "TRECE SOFTWARE", role: "Flutter Developer", period: "2024", project: "Project: Borondo", responsibilities: ["Developed a tourism-focused mobile application using Flutter.", "Implemented creation, editing, sharing and interaction with travel routes.", "Integrated Mapbox, Google Services, Push Notifications, WebSockets and Stripe."] },
    { company: "SIMPLIFIED PRACTICE", role: "Software Developer", period: "2022 – 2024", responsibilities: ["Developed SP Members Portal using Flutter.", "Worked with APIs, payments, file management, chat and push notifications.", "Participated in iOS and Android deployment.", "Developed a multi-tenant React web platform.", "Integrated Google, Twilio and CardConnect services."] },
    { company: "PAYQA", role: "Flutter Developer", period: "2021 – 2022", project: "Project: Ulikme", responsibilities: ["Developed a Flutter mobile dating application.", "Implemented BLoC state management.", "Integrated OAuth, Google, Facebook and chat functionality."] },
  ] },
  projects: { eyebrow: "Selected work", title: "Selected Projects", intro: "A selection of professional products across mobile and web development.", roleLabel: "Role", contributionLabel: "Key contribution", currentProduct: "Current product", featured: "Featured", visitWebsite: "Visit website", googlePlay: "View on Google Play", appStore: "View on the App Store", productVisual: "Mobile product development for the digital sports ecosystem.", entries: [
    { title: "Sportyeah", description: "A digital sports ecosystem for managing clubs, competitions, events, and communities.", role: "Mobile Software Developer", technologies: ["Flutter", "Dart", "Google Services", "iOS Services"], contribution: "Developing and improving tournament, club, profile, and store modules while refining mobile user flows and interfaces.", featured: true },
    { title: "Borondo", description: "A tourism-focused mobile application for creating, editing, sharing, and discovering travel routes.", role: "Flutter Developer", technologies: ["Flutter", "Mapbox", "Google Services", "WebSockets", "Stripe"], contribution: "Built route creation and interaction flows, and integrated mapping, notifications, real-time features, and payments." },
    { title: "SP Members Portal", description: "A mobile portal that connects patients with their clinic through appointments, documents, chat, and notifications.", role: "Software Developer", technologies: ["Flutter", "REST APIs", "Payments", "Push Notifications", "Chat"], contribution: "Developed patient-facing mobile experiences and contributed to API, file-management, payment, chat, and notification integrations." },
    { title: "Simplified Practice Web Platform", description: "A multi-tenant web platform supporting operational workflows for healthcare practices.", role: "Software Developer", technologies: ["React", "TypeScript", "Twilio", "CardConnect", "Google Services"], contribution: "Developed and maintained multi-tenant web features and integrations across communication, payments, and Google services." },
  ] },
  skills: { eyebrow: "Capabilities", title: "Tech Stack", groups: [{ category: "Languages", items: ["JavaScript", "TypeScript", "Dart"] }, { category: "Frontend", items: ["React", "Angular", "HTML5", "CSS3", "Tailwind CSS", "Material UI"] }, { category: "Mobile", items: ["Flutter"] }, { category: "APIs & Integrations", items: ["REST APIs", "GraphQL", "OAuth", "Google Services", "Stripe", "Twilio", "CardConnect"] }, { category: "Platform", items: ["Push Notifications", "iOS Services", "Mapbox", "WebSockets"] }, { category: "Quality & Tools", items: ["SEO", "Accessibility", "Jest", "Mocha", "Git", "GitHub", "Bitbucket"] }] },
  contact: { eyebrow: "Contact", title: "Let's build something great.", description: "I'm open to new opportunities and collaborations in web and mobile development.", getInTouch: "Get in touch", whatsapp: "Contact me on WhatsApp", whatsappMessage: "Hello William, I visited your portfolio and I'd like to get in touch with you.", whatsappAriaLabel: "Contact William on WhatsApp" },
  footer: { rights: "All rights reserved.", backToTop: "Back to top" },
  common: { opensNewTab: "opens in a new tab", english: "English", spanish: "Español", language: "Language", home: "William Puma, home", portraitAlt: "William Puma, Software Developer", projectImageAlt: "project interface" },
} as const;

type DeepStringify<T> = T extends string ? string : T extends readonly (infer Item)[] ? readonly DeepStringify<Item>[] : T extends object ? { readonly [K in keyof T]: DeepStringify<T[K]> } : T;
export type Dictionary = DeepStringify<typeof en>;
