import type { Dictionary } from "./en";

export const es: Dictionary = {
  nav: { about: "Sobre mí", experience: "Experiencia", projects: "Proyectos", skills: "Tecnologías", contact: "Contacto", downloadCv: "Descargar CV", openMenu: "Abrir menú de navegación", closeMenu: "Cerrar menú de navegación" },
  hero: { availability: "Disponible para oportunidades", role: "Software Engineer | Web & Mobile", description: "Diseño y desarrollo productos web y móviles escalables, combinando ingeniería de software, rendimiento y experiencia de usuario.", technologies: "Flutter · React · Angular · TypeScript", viewProjects: "Ver proyectos" },
  about: { eyebrow: "Perfil", title: "Sobre mí", paragraphs: ["Ingeniero en Sistemas Computacionales con experiencia profesional en el desarrollo de productos web y móviles utilizando Flutter, React, Angular, JavaScript, TypeScript y Dart.", "He trabajado en productos internacionales integrando APIs REST, pagos, autenticación OAuth, mapas, notificaciones push, WebSockets y servicios de terceros.", "Disfruto crear productos mantenibles, resolver problemas complejos y diseñar experiencias de usuario intuitivas."] },
  experience: { eyebrow: "Trayectoria", title: "Experiencia profesional", entries: [
    { company: "SPORTYEAH", role: "Desarrollador de Software Móvil", period: "Ago 2025 – Actualidad", responsibilities: ["Desarrollo y mantengo la aplicación móvil de Sportyeah con Flutter y Dart.", "Desarrollo y mejoro los módulos de torneos, clubes, perfil y tienda.", "Integro servicios del ecosistema de Google y servicios de iOS.", "Mejoro flujos de usuario, interfaces y la experiencia móvil general."] },
    { company: "TRECE SOFTWARE", role: "Desarrollador Flutter", period: "2024", project: "Proyecto: Borondo", responsibilities: ["Desarrollé una aplicación móvil enfocada en turismo con Flutter.", "Implementé la creación, edición, compartición e interacción con rutas de viaje.", "Integré Mapbox, Google Services, notificaciones push, WebSockets y Stripe."] },
    { company: "SIMPLIFIED PRACTICE", role: "Desarrollador de Software", period: "2022 – 2024", responsibilities: ["Desarrollé SP Members Portal con Flutter.", "Trabajé con APIs, pagos, gestión de archivos, chat y notificaciones push.", "Participé en el despliegue para iOS y Android.", "Desarrollé una plataforma web multi-tenant con React.", "Integré servicios de Google, Twilio y CardConnect."] },
    { company: "PAYQA", role: "Desarrollador Flutter", period: "2021 – 2022", project: "Proyecto: Ulikme", responsibilities: ["Desarrollé una aplicación móvil de citas con Flutter.", "Implementé la gestión de estado con BLoC.", "Integré OAuth, Google, Facebook y funcionalidades de chat."] },
  ] },
  projects: { eyebrow: "Trabajo seleccionado", title: "Proyectos destacados", intro: "Una selección de productos profesionales de desarrollo móvil y web.", roleLabel: "Rol", contributionLabel: "Contribución clave", currentProduct: "Producto actual", featured: "Destacado", visitWebsite: "Visitar sitio web", googlePlay: "Ver en Google Play", appStore: "Ver en App Store", productVisual: "Desarrollo móvil para el ecosistema digital deportivo.", entries: [
    { title: "Sportyeah", description: "Un ecosistema deportivo digital para gestionar clubes, competiciones, eventos y comunidades.", role: "Desarrollador de Software Móvil", technologies: ["Flutter", "Dart", "Google Services", "iOS Services"], contribution: "Desarrollo y mejoro módulos de torneos, clubes, perfil y tienda, refinando los flujos e interfaces móviles." , featured: true },
    { title: "Borondo", description: "Una aplicación móvil de turismo para crear, editar, compartir y descubrir rutas de viaje.", role: "Desarrollador Flutter", technologies: ["Flutter", "Mapbox", "Google Services", "WebSockets", "Stripe"], contribution: "Construí flujos de creación e interacción de rutas e integré mapas, notificaciones, funcionalidades en tiempo real y pagos." },
    { title: "SP Members Portal", description: "Un portal móvil que conecta a pacientes con su clínica mediante citas, documentos, chat y notificaciones.", role: "Desarrollador de Software", technologies: ["Flutter", "REST APIs", "Payments", "Push Notifications", "Chat"], contribution: "Desarrollé experiencias móviles para pacientes y contribuí a integraciones de APIs, archivos, pagos, chat y notificaciones." },
    { title: "Simplified Practice Web Platform", description: "Una plataforma web multi-tenant que soporta flujos operativos de prácticas de salud.", role: "Desarrollador de Software", technologies: ["React", "TypeScript", "Twilio", "CardConnect", "Google Services"], contribution: "Desarrollé y mantuve funcionalidades web multi-tenant e integraciones de comunicación, pagos y servicios de Google." },
  ] },
  skills: { eyebrow: "Capacidades", title: "Stack tecnológico", groups: [{ category: "Lenguajes", items: ["JavaScript", "TypeScript", "Dart"] }, { category: "Frontend", items: ["React", "Angular", "HTML5", "CSS3", "Tailwind CSS", "Material UI"] }, { category: "Móvil", items: ["Flutter"] }, { category: "APIs e integraciones", items: ["REST APIs", "GraphQL", "OAuth", "Google Services", "Stripe", "Twilio", "CardConnect"] }, { category: "Plataforma", items: ["Push Notifications", "iOS Services", "Mapbox", "WebSockets"] }, { category: "Calidad y herramientas", items: ["SEO", "Accessibility", "Jest", "Mocha", "Git", "GitHub", "Bitbucket"] }] },
  contact: { eyebrow: "Contacto", title: "Construyamos algo increíble.", description: "Estoy abierto a nuevas oportunidades y colaboraciones en desarrollo web y móvil.", getInTouch: "Ponte en contacto", whatsapp: "Escríbeme por WhatsApp", whatsappMessage: "Hola William, visité tu portafolio y me gustaría ponerme en contacto contigo.", whatsappAriaLabel: "Contactar a William por WhatsApp" },
  footer: { rights: "Todos los derechos reservados.", backToTop: "Volver arriba" },
  common: { opensNewTab: "se abre en una pestaña nueva", english: "English", spanish: "Español", language: "Idioma", home: "William Puma, inicio", portraitAlt: "William Puma, Desarrollador de Software", projectImageAlt: "interfaz del proyecto" },
};
